service: caverna-menubot

custom:
  targetBucketName: caverna-menus
  targetSiteUrl: https://caverna.fi/lounas/
  chrome:
    flags:
      - --window-size=1280x1696 # Letter size
      - --hide-scrollbars

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  environment:
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: true
    SLACK_WEBHOOK_URL: ${file(./slack.yml):WebhookUrl}
    TARGET_SITE_URL: ${self:custom.targetSiteUrl}
    TARGET_BUCKET_NAME: ${self:custom.targetBucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.targetBucketName}/*"

plugins:
  - serverless-plugin-chrome

functions:
  screenshot:
    description: Takes picture of Caverna menu
    memorySize: 1536
    timeout: 30
    handler: src/handlers/screenshot.default
    events:
      - http:
          path: screenshot
          method: get
      - schedule: cron(30 7 ? * 2-6 *) # Mon-Fri, 10:30. Just before lunch time.

  slack:
    description: Post menu to slack
    memorySize: 128
    timeout: 10
    handler: src/handlers/slackPoster.default
    events:
      - http:
          path: slack
          method: get
      - s3:
          bucket: ${self:custom.targetBucketName}
          event: s3:ObjectCreated:*

# Uncomment when deploying the first time to create required buckets
# resources:
#   Resources:
#     NewResource:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: ${self:custom.targetBucketName}